export const projects = [
  {
    name: "LifeShots",
    cover: "/projectsBackgrounds/lifeshots.png",
    link: "https://github.com/guisebastiao/lifeshots",
    tecs: ["React", "Tailwind", "ChadCn", "Express", "SQL"],
    star: true,
  },
  {
    name: "ToDoList",
    cover: "/projectsBackgrounds/todo.png",
    link: "https://github.com/guisebastiao/To-Do",
    tecs: ["React", "SQL"],
    star: false,
  },
  {
    name: "Shopping Cart",
    cover: "/projectsBackgrounds/shoppingCart.png",
    link: "https://github.com/guisebastiao/shoppingCart",
    tecs: ["React"],
    star: false,
  },
  {
    name: "Jogo da Velha",
    cover: "/projectsBackgrounds/ticTacToe.png",
    link: "https://github.com/guisebastiao/jogoDaVelha",
    tecs: ["JavaScript"],
    star: false,
  },
  {
    name: "Flappy Bird",
    cover: "/projectsBackgrounds/flappyBird.png",
    link: "https://github.com/guisebastiao/flappyBird",
    tecs: ["JavaScript", "Canvas"],
    star: false,
  },
  {
    name: "Termo",
    cover: "/projectsBackgrounds/termo.png",
    link: "https://github.com/guisebastiao/termo",
    tecs: ["JavaScript"],
    star: false,
  },
  {
    name: "Jogo da Cobrinha",
    cover: "/projectsBackgrounds/snakeGame.png",
    link: "https://github.com/guisebastiao/jogoDaCobrinha",
    tecs: ["JavaScript", "Canvas"],
    star: false,
  },
  {
    name: "Jogo da Memória",
    cover: "/projectsBackgrounds/memoryGame.png",
    link: "https://github.com/guisebastiao/jogoDaCobrinha",
    tecs: ["JavaScript"],
    star: false,
  },
];
