import { VscVscodeInsiders } from "react-icons/vsc";
import { FaJava } from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiSpringboot,
  SiNodedotjs,
  SiNestjs,
  SiExpress,
  SiFastify,
  SiSequelize,
  SiPrisma,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiIntellijidea,
  SiPostman,
  SiDocker,
  SiVite,
  SiFigma,
  SiGit,
  SiGithub,
  SiReactquery,
  SiRedux,
  SiZod,
  SiReacthookform,
  SiReactrouter,
  SiShadcnui,
  SiAuth0,
  SiSpringsecurity,
  SiJsonwebtokens,
  SiNpm,
  SiPnpm,
} from "react-icons/si";

export const stacks = {
  linguagens: [
    { name: "JavaScript", type: "Language", icon: SiJavascript },
    { name: "TypeScript", type: "Language", icon: SiTypescript },
    { name: "Java", type: "Language", icon: FaJava },
    { name: "Python", type: "Language", icon: SiPython },
  ],
  frontend: [
    { name: "React", type: "JavaScript Library", icon: SiReact },
    { name: "NextJS", type: "React Framework", icon: SiNextdotjs },
    { name: "HTML", type: "Hyper Text", icon: SiHtml5 },
    { name: "CSS", type: "Style Sheet", icon: SiCss3 },
    { name: "Tailwind", type: "Framework CSS", icon: SiTailwindcss },
    { name: "Tanstack Query", type: "Library", icon: SiReactquery },
    { name: "Redux", type: "Library", icon: SiRedux },
    { name: "Zod", type: "Library", icon: SiZod },
    { name: "React Hook Form", type: "Library", icon: SiReacthookform },
    { name: "React Router", type: "Library", icon: SiReactrouter },
    { name: "Shadcn/ui", type: "Library", icon: SiShadcnui },
  ],
  backend: [
    { name: "SpringBoot", type: "Java Framework", icon: SiSpringboot },
    { name: "SpringSecurity", type: "Security Framework", icon: SiSpringsecurity },
    { name: "NodeJS", type: "Web Server", icon: SiNodedotjs },
    { name: "NestJS", type: "Node Framework", icon: SiNestjs },
    { name: "Express", type: "Node Framework", icon: SiExpress },
    { name: "Fastify", type: "Node Framework", icon: SiFastify },
    { name: "Sequelize", type: "ORM", icon: SiSequelize },
    { name: "Prisma", type: "ORM", icon: SiPrisma },
    { name: "Auth0", type: "Authentication", icon: SiAuth0 },
    { name: "JWT", type: "Library", icon: SiJsonwebtokens },
  ],
  database: [
    { name: "MySQL", type: "Database", icon: SiMysql },
    { name: "Postgres", type: "Database", icon: SiPostgresql },
    { name: "MongoDB", type: "Database", icon: SiMongodb },
  ],
  ferramentas: [
    { name: "VScode", type: "IDE", icon: VscVscodeInsiders },
    { name: "IntelliJ", type: "IDE", icon: SiIntellijidea },
    { name: "Postman", type: "API", icon: SiPostman },
    { name: "Docker", type: "Container", icon: SiDocker },
    { name: "Vite", type: "Bundler", icon: SiVite },
    { name: "NPM", type: "Package Manager", icon: SiNpm },
    { name: "PNPM", type: "Package Manager", icon: SiPnpm },
    { name: "Figma", type: "UI UX", icon: SiFigma },
    { name: "Git", type: "Versioning", icon: SiGit },
    { name: "GitHub", type: "Repository", icon: SiGithub },
  ],
};
